FROM sawtooth-processor-base-arm:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -y -q python3-requests

RUN apt-get install -y -q python3-yaml

RUN pip3 install pybase64

RUN pip3 install sawtooth-signing

RUN apt-get clean

RUN rm -rf /var/lib/apt/lists/*

WORKDIR /project/iot/pyclient

ENV PATH "$PATH:/project/iot/pyclient"

EXPOSE 3000

CMD unset PYTHONPATH && python3 setup.py clean --all && python3 setup.py build && tail -f /dev/null
