version: '2.1'

services:
  iot-processor:
    container_name: iot-processor
    build:
      context: .
      dockerfile: ./pyprocessor/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator
    volumes:
      - '.:/project/iot/'
    entrypoint: "bash -c \"./iot-tp tcp://validator:4004\""

  iot-client:
    container_name: iot-client
    build:
      context: .
      dockerfile: ./pyclient/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=rest-api,validator,${no_proxy}'
    volumes:
      - '.:/project/iot/'
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - sawtooth-rest-api
#    entrypoint: "bash -c \"sawtooth keygen --force sawtooth && tail -f /dev/null\""
#    entrypoint: "bash -c \"tail -f /dev/null\""
    stop_signal: SIGKILL

  sawtooth-rest-api:
    container_name: rest-api
    image: ooo890/aarch64-sawtooth-rest-api:0.1
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  settings-tp:
    image: ooo890/aarch64-sawtooth-settings-tp:0.1
    depends_on:
      - validator
    command: settings-tp -vvv --connect tcp://validator:4004

  validator:
    container_name: validator
    image: ooo890/aarch64-sawtooth-validator:0.2
    expose:
      - 4004
      - 5050
      - 8000
      - 8800
    user: root
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          sawtooth keygen my_key
          sawset genesis -k /root/.sawtooth/keys/my_key.priv
          sawset proposal create -k /root/.sawtooth/keys/my_key.priv \
            sawtooth.consensus.algorithm.name=Devmode \
            sawtooth.consensus.algorithm.version=0.1 \
            -o config.batch
          sawadm genesis config-genesis.batch config.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050
      "

  devmode-engine:
    image: ooo890/aarch64-sawtooth-devmode-engine:0.1
    expose:
      - 5050
    ports:
      - '5050:5050'
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust --connect tcp://validator:5050
