version: "2.1"

volumes:
  poet-shared:

services:

  validator-1:
    image: ooo890/aarch64-sawtooth-validator:0.2
    container_name: sawtooth-validator-1
    expose:
      - 4004
      - 8800
    ports:
      - '4004:4004'
      - '8800:8800'
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        sawadm keygen --force && \
        mkdir -p /poet-shared/validator-1 && \
        cp -a /etc/sawtooth/keys /poet-shared/validator-1/ && \
        sawtooth-validator -vvv \
            --bind network:tcp://eth0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind consensus:tcp://eth0:5050 \
            --peering dynamic \
            --endpoint tcp://192.168.0.104:8800 \
            --seeds tcp://192.168.0.101:8800 \
            --scheduler parallel \
            --minimum-peer-connectivity 1 \
            --network-auth trust \
            --opentsdb-url http://192.168.0.101:8086 \
            --opentsdb-db metrics
      "
    environment:
      PYTHONPATH: "/project/sawtooth-core/consensus/poet/common:\
        /project/sawtooth-core/consensus/poet/simulator:\
        /project/sawtooth-core/consensus/poet/core"
    stop_signal: SIGKILL

  rest-api-1:
    image: ooo890/aarch64-sawtooth-rest-api:0.1
    container_name: sawtooth-rest-api-1
    expose:
      - 8008
    ports:
      - '8008:8008'
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-1:4004 \
          --bind rest-api-1:8008 \
          --opentsdb-url http://192.168.0.101:8086 \
          --opentsdb-db metrics
      "
    stop_signal: SIGKILL

  iot-processor-1:
    container_name: iot-processor-1
    build:
      context: .
      dockerfile: ./pyprocessor/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator-1
    volumes:
      - '.:/project/iot/'
    entrypoint: "bash -c \"./iot-tp tcp://validator-1:4004\""

  settings-tp-1:
    image: ooo890/aarch64-sawtooth-settings-tp:0.1
    container_name: sawtooth-settings-tp-1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL

  poet-engine-1:
    image: ooo890/aarch64-poet-engine:0.63
    container_name: sawtooth-poet-engine-1
    volumes:
      - poet-shared:/poet-shared
    command: "bash -c \"\
        if [ ! -f /poet-shared/poet-enclave-measurement ]; then \
            poet enclave measurement >> /poet-shared/poet-enclave-measurement; \
        fi && \
        if [ ! -f /poet-shared/poet-enclave-basename ]; then \
            poet enclave basename >> /poet-shared/poet-enclave-basename; \
        fi && \
        if [ ! -f /poet-shared/simulator_rk_pub.pem ]; then \
            cp /etc/sawtooth/simulator_rk_pub.pem /poet-shared; \
        fi && \
        while [ ! -f /poet-shared/validator-1/keys/validator.priv ]; do sleep 1; done && \
        cp -a /poet-shared/validator-1/keys /etc/sawtooth && \
        poet registration create -k /etc/sawtooth/keys/validator.priv -o /poet-shared/poet.batch && \
        poet-engine -C tcp://validator-1:5050 --component tcp://validator-1:4004 \
    \""

  poet-validator-registry-tp-1:
    image: ooo890/aarch64-poet-families:0.3
    container_name: sawtooth-poet-validator-registry-tp-1
    expose:
      - 4004
    ports:
      - '5050:5050'
    command: poet-validator-registry-tp -C tcp://validator-1:4004
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL
