version: "2.1"

volumes:
  raft_shared_data:
    name: raft_shared_data

services:

  admin:
    labels:
      - "com.sawtooth.isolation_id=${ISOLATION_ID:-}"
    build:
      context: .
      dockerfile: admin.Dockerfile
    volumes:
      - raft_shared_data:/shared_data
    command: |
      bash -c "
        ls /shared_data &&
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  validator-1:
    image: ooo890/aarch64-sawtooth-validator:0.2
    container_name: sawtooth-validator-default-1
    expose:
      - 4004
      - 5050
      - 8800
      - 5005
    volumes:
      - raft_shared_data:/shared_data
    command: "bash -c \"\
        while true; do if [ -e /shared_data/validator-1.pub ]; then mv /shared_data/validator-1.priv /etc/sawtooth/keys/validator.priv && mv /shared_data/validator-1.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator -v \
            --endpoint tcp://192.168.0.104:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://192.168.0.101:8800,tcp://192.168.0.105:8800
            --scheduler parallel 
    \""
    depends_on:
      - admin
    stop_signal: SIGKILL

  rest-api-1:
    image: ooo890/aarch64-sawtooth-rest-api:0.1
    container_name: sawtooth-rest-api-default-1
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-1:4004 \
          --bind rest-api-1:8008
      "
    stop_signal: SIGKILL

  iot-processor-1:
    container_name: iot-processor-1
    build:
      context: .
      dockerfile: ./pyprocessor/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator-1
    volumes:
      - '.:/project/iot/'
    entrypoint: "bash -c \"./iot-tp tcp://validator-1:4004\""

  settings-tp-1:
    image: ooo890/aarch64-sawtooth-settings-tp:0.1
    container_name: sawtooth-settings-tp-default-1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL

  raft-engine-1:
    image: ooo890/aarch64-raft-engine:0.1
    container_name: sawtooth-raft-engine-1
    volumes:
      - ..:/project/sawtooth-raft
    command: raft-engine --connect tcp://validator-1:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full
