version: "2.1"

volumes:
  raft_shared_data:

services:

  iot-client:
    container_name: iot-client
    build:
      context: .
      dockerfile: ./pyclient/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=rest-api,validator,${no_proxy}'
    volumes:
      - '.:/project/iot/'
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - rest-api-0
    stop_signal: SIGKILL
  
  validator-0:
    image: ooo890/aarch64-sawtooth-validator:0.2
    container_name: sawtooth-validator-default-0
    expose:
      - 4004
      - 5050
      - 8800
      - 5005
    volumes:
      - raft_shared_data:/shared_data
    command: "bash -c \"\
        sawadm keygen validator-1 && \
        sawadm keygen validator-2 && \
        sawadm keygen && \
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm.name=raft \
          sawtooth.consensus.algorithm.version=0.1 \
          sawtooth.consensus.raft.peers=\\['\\\"'$$(cat /etc/sawtooth/keys/validator.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-1.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-2.pub)'\\\"'\\]
          sawtooth.consensus.raft.period=1 \
          -o config.batch && \
        sawadm genesis \
          config-genesis.batch config.batch && \
        mv /etc/sawtooth/keys/validator-* /shared_data && \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator -v \
            --endpoint tcp://validator-0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-1:8800,tcp://validator-2:8800
            --scheduler parallel \
    \""
    stop_signal: SIGKILL

  validator-1:
    image: ooo890/aarch64-sawtooth-validator:0.2
    container_name: sawtooth-validator-default-1
    expose:
      - 4004
      - 5050
      - 8800
      - 5005
    volumes:
      - raft_shared_data:/shared_data
    command: "bash -c \"\
        while true; do if [ -e /shared_data/validator-1.pub ]; then mv /shared_data/validator-1.priv /etc/sawtooth/keys/validator.priv && mv /shared_data/validator-1.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator -v \
            --endpoint tcp://validator-1:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800,tcp://validator-2:8800
            --scheduler parallel \
    \""
    stop_signal: SIGKILL

  validator-2:
    image: ooo890/aarch64-sawtooth-validator:0.2
    container_name: sawtooth-validator-default-2
    expose:
      - 4004
      - 5050
      - 8800
      - 5005
    volumes:
      - raft_shared_data:/shared_data
    command: "bash -c \"\
        while true; do if [ -e /shared_data/validator-2.pub ]; then mv /shared_data/validator-2.priv /etc/sawtooth/keys/validator.priv && mv /shared_data/validator-2.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator -v \
            --endpoint tcp://validator-2:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800,tcp://validator-1:8800
            --scheduler parallel \
    \""
    stop_signal: SIGKILL

  rest-api-0:
    image: ooo890/aarch64-sawtooth-rest-api:0.1
    container_name: sawtooth-rest-api-default-0
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-0:4004 \
          --bind rest-api-0:8008
      "
    stop_signal: SIGKILL

  rest-api-1:
    image: ooo890/aarch64-sawtooth-rest-api:0.1
    container_name: sawtooth-rest-api-default-1
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-1:4004 \
          --bind rest-api-1:8008
      "
    stop_signal: SIGKILL

  rest-api-2:
    image: ooo890/aarch64-sawtooth-rest-api:0.1
    container_name: sawtooth-rest-api-default-2
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-2:4004 \
          --bind rest-api-2:8008
      "
    stop_signal: SIGKILL
   
  iot-processor-0:
    container_name: iot-processor-0
    build:
      context: .
      dockerfile: ./pyprocessor/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator-0
    volumes:
      - '.:/project/iot/'
    entrypoint: "bash -c \"./iot-tp tcp://validator-0:4004\""

  iot-processor-1:
    container_name: iot-processor-1
    build:
      context: .
      dockerfile: ./pyprocessor/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator-1
    volumes:
      - '.:/project/iot/'
    entrypoint: "bash -c \"./iot-tp tcp://validator-1:4004\""

  iot-processor-2:
    container_name: iot-processor-2
    build:
      context: .
      dockerfile: ./pyprocessor/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator-2
    volumes:
      - '.:/project/iot/'
    entrypoint: "bash -c \"./iot-tp tcp://validator-2:4004\""

  settings-tp-0:
    image: ooo890/aarch64-sawtooth-settings-tp:0.1
    container_name: sawtooth-settings-tp-default-0
    expose:
      - 4004
    command: settings-tp -C tcp://validator-0:4004
    stop_signal: SIGKILL

  settings-tp-1:
    image: ooo890/aarch64-sawtooth-settings-tp:0.1
    container_name: sawtooth-settings-tp-default-1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL

  settings-tp-2:
    image: ooo890/aarch64-sawtooth-settings-tp:0.1
    container_name: sawtooth-settings-tp-default-2
    expose:
      - 4004
    command: settings-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL

  raft-engine-0:
    image: ooo890/aarch64-raft-engine:0.1
    container_name: sawtooth-raft-engine-0
    volumes:
      - ..:/project/sawtooth-raft
    command: raft-engine --connect tcp://validator-0:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

  raft-engine-1:
    image: ooo890/aarch64-raft-engine:0.1
    container_name: sawtooth-raft-engine-1
    volumes:
      - ..:/project/sawtooth-raft
    command: raft-engine --connect tcp://validator-1:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

  raft-engine-2:
    image: ooo890/aarch64-raft-engine:0.1
    container_name: sawtooth-raft-engine-2
    volumes:
      - ..:/project/sawtooth-raft
    command: raft-engine --connect tcp://validator-2:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

networks:
  frontend-network:
    external: true
