version: "2.1"

volumes:
  poet-shared:

services:

  iot-client:
    container_name: iot-client
    build:
      context: .
      dockerfile: ./pyclient/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=rest-api,validator,${no_proxy}'
    volumes:
      - '.:/project/iot/'
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - rest-api-0
    stop_signal: SIGKILL

  validator-2:
    image: ooo890/aarch64-sawtooth-validator:0.2
    container_name: sawtooth-validator-default-2
    expose:
      - 4004
      - 8800
    ports:
      - '4004:4004'
      - '8800:8800'
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        sawadm keygen --force && \
        mkdir -p /poet-shared/validator-2 && \
        cp -a /etc/sawtooth/keys /poet-shared/validator-2/ && \
        sawtooth-validator -vvv \
            --bind network:tcp://eth0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind consensus:tcp://eth0:5050 \
            --peering dynamic \
            --endpoint tcp://192.168.2.5:8800 \
            --seeds tcp://192.168.2.4:8800 \
            --scheduler serial \
            --minimum-peer-connectivity 1 \
            --network-auth trust
      "
    environment:
      PYTHONPATH: "/project/sawtooth-core/consensus/poet/common:\
        /project/sawtooth-core/consensus/poet/simulator:\
        /project/sawtooth-core/consensus/poet/core"
    stop_signal: SIGKILL

  rest-api-0:
    image: ooo890/aarch64-sawtooth-rest-api:0.1
    container_name: sawtooth-rest-api-default-0
    expose:
      - 8008
    ports:
      - '8008:8008'
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-2:4004 \
          --bind rest-api-0:8008
      "
    stop_signal: SIGKILL

  iot-processor-0:
    container_name: iot-processor-0
    build:
      context: .
      dockerfile: ./pyprocessor/Dockerfile.arm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator-2
    volumes:
      - '.:/project/iot/'
    entrypoint: "bash -c \"./iot-tp tcp://validator-2:4004\""

  settings-tp-0:
    image: ooo890/aarch64-sawtooth-settings-tp:0.1
    container_name: sawtooth-settings-tp-default-0
    expose:
      - 4004
    command: settings-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL

  poet-engine-0:
    image: ooo890/aarch64-poet-engine:0.63
    container_name: sawtooth-poet-engine-0
    volumes:
      - poet-shared:/poet-shared
    command: "bash -c \"\
        if [ ! -f /poet-shared/poet-enclave-measurement ]; then \
            poet enclave measurement >> /poet-shared/poet-enclave-measurement; \
        fi && \
        if [ ! -f /poet-shared/poet-enclave-basename ]; then \
            poet enclave basename >> /poet-shared/poet-enclave-basename; \
        fi && \
        if [ ! -f /poet-shared/simulator_rk_pub.pem ]; then \
            cp /etc/sawtooth/simulator_rk_pub.pem /poet-shared; \
        fi && \
        while [ ! -f /poet-shared/validator-2/keys/validator.priv ]; do sleep 1; done && \
        cp -a /poet-shared/validator-2/keys /etc/sawtooth && \
        poet registration create -k /etc/sawtooth/keys/validator.priv -o /poet-shared/poet.batch && \
        poet-engine -C tcp://validator-2:5050 --component tcp://validator-2:4004 \
    \""

  poet-validator-registry-tp-0:
    image: ooo890/aarch64-poet-families:0.3
    container_name: sawtooth-poet-validator-registry-tp-0
    expose:
      - 4004
    ports:
      - '5050:5050'
    command: poet-validator-registry-tp -C tcp://validator-2:4004
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL
